server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3333/wangyi
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset:utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  cache:
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30s
mybatis:
  configuration:
    map-underscore-to-camel-case: true